/* =====================================================================
   Game Data — The Muddy Trail, The Iron Hollows & The Ashen Waste
   Enemies, items, NPCs, scenes, bounties, quests, death quotes
   ===================================================================== */

const ENEMIES={
// === TIER 1 — COMMON (8 total) ===
gray_ooze:{name:'Gray Ooze',id:'gray_ooze',tier:1,lore:'A shimmering mass of corrosive slime that oozes along forest trails, drawn to warmth and movement. Slow but relentless.',hp:15,mHP:15,atk:5,def:0,dD:4,dB:1,preferredZone:'close',xp:50,gold:5,
  loot:[{item:'hpot',weight:50},{item:null,weight:50}]},
bog_wraith:{name:'Bog Wraith',id:'bog_wraith',tier:1,lore:'A half-material spectre born of drowned souls and marsh gas. It drifts through the mist, reaching with cold, grasping tendrils.',hp:14,mHP:14,atk:5,def:0,dD:4,dB:1,preferredZone:'close',xp:60,gold:6,
  loot:[{item:'marsh_root',weight:35},{item:'mpot',weight:30},{item:null,weight:35}]},
moss_rat:{name:'Moss Rat',id:'moss_rat',tier:1,lore:'An oversized rodent covered in damp green moss. More nuisance than threat, but its teeth are sharp.',hp:10,mHP:10,atk:3,def:0,dD:4,dB:0,preferredZone:'close',xp:30,gold:3,
  loot:[{item:'marsh_root',weight:40},{item:null,weight:60}]},
marsh_toad:{name:'Marsh Toad',id:'marsh_toad',tier:1,lore:'A bloated amphibian the size of a dog. It spits caustic slime and retreats into the muck.',hp:12,mHP:12,atk:4,def:0,dD:4,dB:0,preferredZone:'mid',xp:35,gold:3,
  loot:[{item:'marsh_root',weight:50},{item:null,weight:50}]},
spore_mite:{name:'Spore Mite',id:'spore_mite',tier:1,lore:'A thumb-sized insect that travels in swarms. Individually harmless; in numbers, they fill the air with choking spores.',hp:10,mHP:10,atk:3,def:0,dD:4,dB:0,preferredZone:'mid',xp:30,gold:2,
  loot:[{item:null,weight:70},{item:'hpot',weight:30}]},
ember_beetle:{name:'Ember Beetle',id:'ember_beetle',tier:1,lore:'A fist-sized beetle with a carapace that glows like a dying coal. It skitters toward warmth and bites reflexively.',hp:11,mHP:11,atk:4,def:0,dD:4,dB:0,preferredZone:'close',xp:35,gold:3,
  loot:[{item:null,weight:60},{item:'hpot',weight:40}]},
ash_worm:{name:'Ash Worm',id:'ash_worm',tier:1,lore:'A pale, segmented worm that burrows through volcanic ash. It surfaces to feed on anything organic.',hp:13,mHP:13,atk:4,def:0,dD:4,dB:1,preferredZone:'close',xp:40,gold:4,
  loot:[{item:'ration',weight:40},{item:null,weight:60}]},
tunnel_bat:{name:'Tunnel Bat',id:'tunnel_bat',tier:1,lore:'A cave-dwelling bat with a wingspan wider than a man is tall. Its screech disorients, and its fangs draw blood.',hp:10,mHP:10,atk:4,def:0,dD:4,dB:0,preferredZone:'mid',xp:30,gold:3,
  loot:[{item:null,weight:65},{item:'hpot',weight:35}]},

// === TIER 2 — UNCOMMON (12 total) ===
giant_spider:{name:'Giant Spider',id:'giant_spider',tier:2,lore:'A forest-dwelling predator that lurks in the canopy, spitting venom and descending on silk threads to ambush travelers below.',hp:18,mHP:18,atk:6,def:1,dD:6,dB:1,preferredZone:'mid',xp:75,gold:8,
  onHit:{effect:'poison',chance:40,duration:3,dmg:2},
  loot:[{item:'antidote',weight:40},{item:'hpot',weight:25},{item:null,weight:35}]},
dire_wolf:{name:'Dire Wolf',id:'dire_wolf',tier:2,lore:'A massive grey wolf, scarred and cunning. It circles its prey with unnerving patience before closing with terrifying speed.',hp:22,mHP:22,atk:7,def:1,dD:8,dB:1,preferredZone:'close',xp:90,gold:12,
  onHit:{effect:'bleed',chance:30,duration:3,dmg:1},
  loot:[{item:'wolf_pelt',weight:35},{item:'hpot',weight:20},{item:'mpot',weight:15},{item:null,weight:30}]},
venomfang_snake:{name:'Venomfang Snake',id:'venomfang_snake',tier:2,lore:'A black-scaled serpent with translucent fangs. Its venom works fast, shutting down muscles within minutes.',hp:16,mHP:16,atk:6,def:0,dD:6,dB:1,preferredZone:'close',xp:70,gold:7,
  onHit:{effect:'poison',chance:45,duration:3,dmg:2},
  loot:[{item:'antidote',weight:50},{item:null,weight:50}]},
shadow_hound:{name:'Shadow Hound',id:'shadow_hound',tier:2,lore:'A spectral canine that flickers between solid and immaterial. Its claws leave wounds that refuse to close.',hp:20,mHP:20,atk:6,def:1,dD:6,dB:1,preferredZone:'close',xp:80,gold:9,
  onHit:{effect:'bleed',chance:35,duration:3,dmg:1},
  loot:[{item:'bandage',weight:40},{item:'hpot',weight:25},{item:null,weight:35}]},
fungal_horror:{name:'Fungal Horror',id:'fungal_horror',tier:2,lore:'A shambling mass of rotting vegetation animated by parasitic fungi. It releases clouds of toxic spores.',hp:20,mHP:20,atk:5,def:1,dD:6,dB:0,preferredZone:'mid',xp:75,gold:7,
  onHit:{effect:'poison',chance:35,duration:2,dmg:2},
  loot:[{item:'antidote',weight:35},{item:'mushroom_brew',weight:30},{item:null,weight:35}]},
ironscale_lizard:{name:'Ironscale Lizard',id:'ironscale_lizard',tier:2,lore:'A thick-bodied lizard with metallic scales. Slow but armored, it charges with lowered head and snapping jaws.',hp:22,mHP:22,atk:6,def:2,dD:6,dB:1,preferredZone:'close',xp:80,gold:9,
  loot:[{item:'iron_shard',weight:20},{item:'hpot',weight:30},{item:null,weight:50}]},
ghoul:{name:'Ghoul',id:'ghoul',tier:2,lore:'A corpse that refused to stay buried. Its touch paralyzes, and its hunger is endless.',hp:18,mHP:18,atk:6,def:0,dD:6,dB:1,preferredZone:'close',xp:75,gold:8,tags:['undead'],
  onHit:{effect:'stun',chance:20,duration:1,dmg:0},
  loot:[{item:'smelling_salts',weight:35},{item:'hpot',weight:25},{item:null,weight:40}]},
bone_sentinel:{name:'Bone Sentinel',id:'bone_sentinel',tier:2,lore:'An animate skeleton in rusted armor. It stands guard long after its master turned to dust.',hp:20,mHP:20,atk:6,def:2,dD:6,dB:0,preferredZone:'close',xp:80,gold:8,tags:['undead'],
  loot:[{item:'iron_sword',weight:10},{item:'hpot',weight:30},{item:null,weight:60}]},
rock_troll:{name:'Rock Troll',id:'rock_troll',tier:2,lore:'A squat, stone-skinned brute that lurks under bridges and in shallow caves. Stupid but dangerously strong.',hp:24,mHP:24,atk:7,def:1,dD:8,dB:0,preferredZone:'close',xp:90,gold:12,
  loot:[{item:'troll_blood',weight:15},{item:'hpot',weight:30},{item:null,weight:55}]},
wyvern_hatchling:{name:'Wyvern Hatchling',id:'wyvern_hatchling',tier:2,lore:'A juvenile wyvern, too young to fly but old enough to kill. Its venomous tail whips with surprising reach.',hp:18,mHP:18,atk:6,def:1,dD:6,dB:1,preferredZone:'mid',xp:85,gold:10,
  onHit:{effect:'poison',chance:25,duration:2,dmg:1},
  loot:[{item:'hpot',weight:40},{item:null,weight:60}]},

// === TIER 3 — DANGEROUS (9 total) ===
cave_crawler:{name:'Cave Crawler',id:'cave_crawler',tier:3,lore:'A bloated, segmented horror that drags itself through the tunnels on dozens of pale legs. Its chitinous hide turns blades.',hp:25,mHP:25,atk:6,def:2,dD:6,dB:1,preferredZone:'close',xp:80,gold:8,
  onHit:{effect:'slow',chance:25,duration:2,dmg:0},
  loot:[{item:'dwarven_ale',weight:40},{item:'hpot',weight:25},{item:null,weight:35}]},
flame_elemental:{name:'Flame Elemental',id:'flame_elemental',tier:3,lore:'A pillar of living fire that drifts through volcanic fissures. Its touch ignites flesh and warps metal.',hp:22,mHP:22,atk:7,def:1,dD:8,dB:0,preferredZone:'mid',xp:100,gold:12,
  onHit:{effect:'burn',chance:40,duration:3,dmg:2},
  loot:[{item:'burn_salve',weight:35},{item:'ghpot',weight:20},{item:null,weight:45}]},
darkwood_treant:{name:'Darkwood Treant',id:'darkwood_treant',tier:3,lore:'An ancient tree twisted by dark magic into a shambling predator. Its roots entangle; its branches crush.',hp:28,mHP:28,atk:6,def:3,dD:6,dB:1,preferredZone:'close',xp:95,gold:10,
  onHit:{effect:'slow',chance:30,duration:2,dmg:0},
  loot:[{item:'marsh_root',weight:30},{item:'ghpot',weight:25},{item:null,weight:45}]},
banshee:{name:'Banshee',id:'banshee',tier:3,lore:'The wailing spirit of a woman betrayed. Her scream curdles the blood and clouds the mind.',hp:22,mHP:22,atk:7,def:1,dD:6,dB:1,preferredZone:'mid',xp:100,gold:12,tags:['undead'],
  onHit:{effect:'curse',chance:35,duration:3,dmg:0},
  loot:[{item:'purification_scroll',weight:35},{item:'banshee_essence',weight:15},{item:null,weight:50}]},
chimera_spawn:{name:'Chimera Spawn',id:'chimera_spawn',tier:3,lore:'A malformed beast with the heads of a lion, goat, and serpent. Each head attacks independently.',hp:26,mHP:26,atk:7,def:2,dD:8,dB:0,preferredZone:'close',xp:110,gold:14,
  loot:[{item:'ghpot',weight:30},{item:'strength_tonic',weight:15},{item:null,weight:55}]},
corrupted_knight:{name:'Corrupted Knight',id:'corrupted_knight',tier:3,lore:'Once a champion of the realm, now a shell of rusted armor animated by spite. Its sword remembers its training.',hp:28,mHP:28,atk:8,def:2,dD:8,dB:1,preferredZone:'close',xp:115,gold:15,tags:['undead'],
  onHit:{effect:'bleed',chance:30,duration:3,dmg:1},
  loot:[{item:'steel_sword',weight:10},{item:'scale_mail',weight:8},{item:'ghpot',weight:25},{item:null,weight:57}]},
crystal_golem:{name:'Crystal Golem',id:'crystal_golem',tier:3,lore:'A construct of living quartz, refracting light into blinding patterns. Each blow sends razor shards in all directions.',hp:30,mHP:30,atk:6,def:3,dD:6,dB:1,preferredZone:'close',xp:100,gold:12,
  onHit:{effect:'blind',chance:25,duration:2,dmg:0},
  loot:[{item:'iron_shard',weight:30},{item:'ghpot',weight:20},{item:null,weight:50}]},
plague_bearer:{name:'Plague Bearer',id:'plague_bearer',tier:3,lore:'A shambling corpse wreathed in flies and decay. Its mere proximity sickens; its touch brings fever and rot.',hp:24,mHP:24,atk:7,def:1,dD:6,dB:1,preferredZone:'close',xp:105,gold:11,tags:['undead'],
  onHit:{effect:'poison',chance:45,duration:3,dmg:2},
  loot:[{item:'antidote',weight:40},{item:'ghpot',weight:20},{item:null,weight:40}]},
wyvern:{name:'Wyvern',id:'wyvern',tier:3,lore:'A fully grown wyvern, scales hardened by years of territorial battles. It dives from above, striking with talons and venomous tail.',hp:26,mHP:26,atk:8,def:2,dD:8,dB:0,preferredZone:'mid',xp:120,gold:14,
  onHit:{effect:'poison',chance:30,duration:2,dmg:2},
  loot:[{item:'dragon_scale',weight:10},{item:'ghpot',weight:25},{item:null,weight:65}]},

// === TIER 4 — ELITE (7 total) ===
mine_shade:{name:'Mine Shade',id:'mine_shade',tier:4,lore:'A flickering silhouette that darts between pillars of stone. It strikes from impossible angles, its touch numbing mind and muscle.',hp:12,mHP:12,atk:8,def:0,dD:4,dB:1,preferredZone:'mid',xp:100,gold:10,
  onHit:{effect:'stun',chance:20,duration:1,dmg:0},
  loot:[{item:'mpot',weight:35},{item:'antidote',weight:25},{item:null,weight:40}]},
death_knight:{name:'Death Knight',id:'death_knight',tier:4,lore:'A lord of the undead in blackened plate. Two curses attend its blade: decay and endless bleeding.',hp:28,mHP:28,atk:9,def:3,dD:8,dB:2,preferredZone:'close',xp:150,gold:20,tags:['undead'],
  onHit:{effect:'curse',chance:30,duration:3,dmg:0},
  loot:[{item:'enchanted_blade',weight:8},{item:'knights_plate',weight:5},{item:'ghpot',weight:30},{item:null,weight:57}]},
void_stalker:{name:'Void Stalker',id:'void_stalker',tier:4,lore:'A creature from between worlds. It flickers in and out of reality, striking from angles that shouldn\'t exist.',hp:22,mHP:22,atk:9,def:1,dD:8,dB:1,preferredZone:'mid',xp:140,gold:18,
  onHit:{effect:'blind',chance:35,duration:2,dmg:0},
  loot:[{item:'eye_drops',weight:30},{item:'shadow_cloak',weight:8},{item:'ghpot',weight:25},{item:null,weight:37}]},
ash_wyrm:{name:'Ash Wyrm',id:'ash_wyrm',tier:4,lore:'A serpentine dragon that nests in volcanic vents. Its breath is superheated ash that chars flesh and blinds eyes.',hp:26,mHP:26,atk:9,def:2,dD:8,dB:1,preferredZone:'mid',xp:145,gold:18,
  onHit:{effect:'burn',chance:40,duration:3,dmg:2},
  loot:[{item:'dragon_scale',weight:20},{item:'burn_salve',weight:25},{item:'ghpot',weight:20},{item:null,weight:35}]},
lich_apprentice:{name:'Lich Apprentice',id:'lich_apprentice',tier:4,lore:'A mage who traded death for undeath. Its mastery of dark magic is incomplete but potent enough to end the unwary.',hp:20,mHP:20,atk:8,def:1,dD:6,dB:2,preferredZone:'far',xp:140,gold:18,tags:['undead'],
  onHit:{effect:'curse',chance:40,duration:3,dmg:0},
  loot:[{item:'purification_scroll',weight:30},{item:'lich_dust',weight:15},{item:'gmpot',weight:20},{item:null,weight:35}]},
storm_elemental:{name:'Storm Elemental',id:'storm_elemental',tier:4,lore:'A howling vortex of wind and lightning. It moves erratically, striking with bolts that leave muscles locked and twitching.',hp:24,mHP:24,atk:9,def:1,dD:8,dB:1,preferredZone:'far',xp:145,gold:18,
  onHit:{effect:'stun',chance:25,duration:1,dmg:0},
  loot:[{item:'smelling_salts',weight:30},{item:'gmpot',weight:25},{item:null,weight:45}]},
troll_warlord:{name:'Troll Warlord',id:'troll_warlord',tier:4,lore:'A massive troll chieftain covered in war paint and old scars. Its crushing blows leave victims weakened and broken.',hp:28,mHP:28,atk:10,def:2,dD:10,dB:0,preferredZone:'close',xp:155,gold:22,
  onHit:{effect:'weaken',chance:30,duration:3,dmg:0},
  loot:[{item:'troll_blood',weight:25},{item:'war_hammer',weight:5},{item:'ghpot',weight:25},{item:null,weight:45}]},

// === TIER 5 — BOSS (5 total) ===
iron_golem:{name:'Iron Golem',id:'iron_golem',tier:5,lore:'A construct of living iron, forged in the old dwarven wars and left to guard the deep forge. It moves with grinding deliberation, each blow like a collapsing wall.',hp:35,mHP:35,atk:9,def:3,dD:10,dB:1,preferredZone:'close',xp:150,gold:20,
  loot:[{item:'iron_shard',weight:50},{item:'hpot',weight:25},{item:null,weight:25}]},
elder_dragon:{name:'Elder Dragon',id:'elder_dragon',tier:5,lore:'The oldest living dragon in the Ashen Waste. Its scales are volcanic glass, its breath a river of liquid fire. Kingdoms have fallen to feed its hunger.',hp:45,mHP:45,atk:11,def:3,dD:10,dB:2,preferredZone:'mid',xp:300,gold:50,
  onHit:{effect:'burn',chance:50,duration:3,dmg:3},
  loot:[{item:'dragon_scale',weight:60},{item:'flaming_sword',weight:10},{item:null,weight:30}]},
lich_king:{name:'Lich King',id:'lich_king',tier:5,lore:'The master of undeath, enthroned in a crypt of crystallized souls. His magic unravels the will to live.',hp:40,mHP:40,atk:10,def:2,dD:8,dB:3,preferredZone:'far',xp:280,gold:45,tags:['undead'],
  onHit:{effect:'curse',chance:45,duration:4,dmg:0},
  loot:[{item:'lich_dust',weight:50},{item:'grimoire',weight:10},{item:null,weight:40}]},
ancient_construct:{name:'Ancient Construct',id:'ancient_construct',tier:5,lore:'A war machine from a forgotten age. Powered by a gem that pulses with dying starlight. Every joint screams with neglected centuries.',hp:50,mHP:50,atk:10,def:4,dD:10,dB:1,preferredZone:'close',xp:300,gold:50,
  loot:[{item:'iron_shard',weight:40},{item:'knights_plate',weight:10},{item:null,weight:50}]},
demon_lord:{name:'Demon Lord',id:'demon_lord',tier:5,lore:'A being of pure malice given form. It wields fear as a weapon and pain as a tool. Where it walks, hope dies.',hp:42,mHP:42,atk:11,def:2,dD:10,dB:2,preferredZone:'close',xp:320,gold:55,
  onHit:{effect:'weaken',chance:35,duration:3,dmg:0},
  loot:[{item:'demon_horn',weight:50},{item:'enchanted_blade',weight:10},{item:null,weight:40}]}
};

const ITEMS={
// === CONSUMABLES ===
hpot:{name:'Health Potion',t:'consumable',wt:0,heal:10,desc:'Restores 10 HP.',value:8},
mpot:{name:'Mana Potion',t:'consumable',wt:0,mana:10,desc:'Restores 10 MP.',value:8},
ghpot:{name:'Greater Health Potion',t:'consumable',wt:0,heal:20,desc:'Restores 20 HP.',value:18},
gmpot:{name:'Greater Mana Potion',t:'consumable',wt:0,mana:20,desc:'Restores 20 MP.',value:18},
elixir:{name:'Elixir',t:'consumable',wt:0,heal:10,mana:10,desc:'Restores 10 HP and 10 MP.',value:22},
antidote:{name:'Antidote',t:'consumable',wt:0,cure:'poison',desc:'Cures poison.',value:6},
bandage:{name:'Bandage',t:'consumable',wt:0,cure:'bleed',desc:'Stops bleeding.',value:6},
smelling_salts:{name:'Smelling Salts',t:'consumable',wt:0,cure:'stun',desc:'Clears stun.',value:6},
burn_salve:{name:'Burn Salve',t:'consumable',wt:0,cure:'burn',desc:'Soothes burns.',value:6},
purification_scroll:{name:'Purification Scroll',t:'consumable',wt:0,cure:'curse',desc:'Lifts curses.',value:10},
eye_drops:{name:'Eye Drops',t:'consumable',wt:0,cure:'blind',desc:'Restores sight.',value:6},
strength_tonic:{name:'Strength Tonic',t:'consumable',wt:0,heal:5,desc:'A bitter draught. Restores 5 HP.',value:8},
focus_draught:{name:'Focus Draught',t:'consumable',wt:0,mana:8,desc:'Sharpens the mind. Restores 8 MP.',value:8},
ration:{name:'Ration',t:'consumable',wt:0,heal:3,desc:'Dry bread and jerky. Restores 3 HP.',value:3},
mushroom_brew:{name:'Mushroom Brew',t:'consumable',wt:0,heal:8,desc:'A pungent fungal tea. Restores 8 HP.',value:6},
marsh_root:{name:'Marsh Root',t:'consumable',wt:0,heal:5,desc:'A bitter root. Restores 5 HP.',value:5},
dwarven_ale:{name:'Dwarven Ale',t:'consumable',wt:0,heal:3,cure:'bleed',desc:'Burns going down. Cures bleed, heals 3 HP.',value:10},

// === WEAPONS — MELEE ===
iron_sword:{name:'Iron Sword',t:'melee',wt:1,dD:6,dB:1,desc:'Melee, 1d6+1. Reliable.',value:20},
steel_sword:{name:'Steel Sword',t:'melee',wt:1,dD:8,dB:1,desc:'Melee, 1d8+1. Well-forged.',value:35},
enchanted_blade:{name:'Enchanted Blade',t:'melee',wt:1,dD:8,dB:3,desc:'Melee, 1d8+3. Glows faintly blue.',value:60},
war_hammer:{name:'War Hammer',t:'melee',wt:2,dD:10,dB:1,desc:'Melee, 1d10+1. Two-handed.',twoHand:true,value:40},
mace:{name:'Mace',t:'melee',wt:1,dD:6,dB:2,desc:'Melee, 1d6+2. Crushes armor.',value:25},
rapier:{name:'Rapier',t:'melee',wt:0,dD:6,dB:1,desc:'Melee, 1d6+1. Light and fast.',value:22},
broadsword:{name:'Broadsword',t:'melee',wt:1,dD:8,dB:0,desc:'Melee, 1d8. Versatile blade.',value:28},
flaming_sword:{name:'Flaming Sword',t:'melee',wt:1,dD:8,dB:2,desc:'Melee, 1d8+2. Wreathed in flame.',value:70},
halberd:{name:'Halberd',t:'melee',wt:2,dD:10,dB:0,desc:'Melee, 1d10. Two-handed reach.',twoHand:true,value:35},
bone_cleaver:{name:'Bone Cleaver',t:'melee',wt:2,dD:10,dB:2,desc:'Melee, 1d10+2. Two-handed. Grim.',twoHand:true,value:50},

// === WEAPONS — RANGED ===
longbow:{name:'Longbow',t:'ranged',wt:1,dD:8,dB:0,desc:'Ranged, 1d8. 12 arrows.',ammo:12,twoHand:true,value:30},
crossbow:{name:'Crossbow',t:'ranged',wt:1,dD:10,dB:0,desc:'Ranged, 1d10. 6 bolts.',ammo:6,twoHand:true,value:40},
throwing_knives:{name:'Throwing Knives',t:'ranged',wt:0,dD:4,dB:3,desc:'Ranged, 1d4+3. 12 knives.',ammo:12,value:25},

// === ARMOR ===
padded_armor:{name:'Padded Armor',t:'armor',wt:0,dB:1,desc:'+1 defense (Light).',value:15},
scale_mail:{name:'Scale Mail',t:'armor',wt:1,dB:2,desc:'+2 defense (Medium).',value:30},
iron_plate:{name:'Iron Plate',t:'armor',wt:2,dB:3,desc:'+3 defense (Heavy).',value:50},
knights_plate:{name:"Knight's Plate",t:'armor',wt:2,dB:4,desc:'+4 defense (Heavy).',value:80},
mage_vestments:{name:'Mage Vestments',t:'armor',wt:0,dB:0,desc:'+0 defense. Enhances magic.',value:20},
shadow_cloak:{name:'Shadow Cloak',t:'armor',wt:0,dB:1,desc:'+1 defense (Light). Whisper-quiet.',value:35},

// === OFFHAND ===
iron_shield:{name:'Iron Shield',t:'shield',wt:1,blk:3,desc:'+3 block (Medium).',value:25},
tower_shield:{name:'Tower Shield',t:'shield',wt:2,blk:4,desc:'+4 block (Heavy).',value:45},
grimoire:{name:'Grimoire',t:'spellbook',wt:0,desc:'Dark tome. Required for spell abilities.',value:40},
crystal_orb:{name:'Crystal Orb',t:'spellbook',wt:0,desc:'Arcane focus. Required for spell abilities.',value:45},

// === MISC/LOOT ===
wolf_pelt:{name:'Wolf Pelt',t:'misc',wt:1,desc:'A thick grey pelt. Proof of the kill.',value:15},
iron_shard:{name:'Iron Shard',t:'misc',wt:1,desc:'A jagged fragment of living iron. Warm to the touch.',value:20},
dragon_scale:{name:'Dragon Scale',t:'misc',wt:1,desc:'A scale of volcanic glass. Almost indestructible.',value:50},
lich_dust:{name:'Lich Dust',t:'misc',wt:0,desc:'Powdered bone from an undead mage. Radiates cold.',value:40},
demon_horn:{name:'Demon Horn',t:'misc',wt:1,desc:'A curved horn of obsidian black. Pulses with malice.',value:55},
troll_blood:{name:'Troll Blood',t:'misc',wt:0,desc:'Viscous green blood. Alchemists pay well for this.',value:30},
banshee_essence:{name:'Banshee Essence',t:'misc',wt:0,desc:'Bottled wailing. Useful in rituals.',value:35},
guide:{name:"Player's Guide",t:'key',wt:0,desc:'A weathered guide to combat, creatures, and the world.',undrop:true}
};

const NPCS={
// === ORIGINAL NPCs ===
aldric:{name:'Aldric',title:'The Gatekeeper',desc:'A weathered guardsman stands beside the trail gate, watching with tired but alert eyes.'},
mira:{name:'Mira',title:'The Healer',desc:'A woman in green robes tends herbs near the shrine. She looks up and smiles warmly.'},
garrett:{name:'Garrett',title:'The Peddler',desc:'A thin man in a patched cloak, his pack brimming with oddments. He eyes your backpack appraisingly.'},
torgun:{name:'Torgun',title:'The Lost Miner',desc:'A stocky dwarf sits against the wall, clutching a battered pickaxe. He looks up with hollow eyes.'},
brynn:{name:'Brynn',title:'The Innkeeper',desc:'A broad-shouldered woman polishes a mug behind the bar, her scarred hands betraying a life before innkeeping.'},

// === NEW NPCs (data-driven dialogue) ===
elara:{name:'Elara',title:'The Armorsmith',desc:'A tall woman with soot-streaked arms hammers at an anvil. Racks of weapons and armor gleam behind her.',
  shop:{stock:[{key:'iron_sword',price:25},{key:'steel_sword',price:40},{key:'mace',price:30},{key:'rapier',price:28},{key:'scale_mail',price:35},{key:'iron_plate',price:55},{key:'iron_shield',price:30}]},
  dialogue:{
    initial:{text:'"Fresh face at the forge. I\'m Elara. If you need steel or plate, you\'ve come to the right anvil. Browse my wares — I stand behind every piece."',options:[{text:'"Show me your wares."',next:'shop_node'},{text:'"Tell me about yourself."',next:'about'},{text:'"Not now."',next:null}]},
    returning:{text:'"Back again? I\'ve got new stock if you\'re looking."',options:[{text:'"Show me your wares."',next:'shop_node'},{text:'"Just passing through."',next:null}]},
    shop_node:{text:'"Take your time. Quality costs, but it\'ll save your life."',effect:'shop',options:[{text:'"Done browsing."',next:null}]},
    about:{text:'"Used to be a soldier. Took a lance through the shoulder at Blackmoor. Can\'t swing a sword like I used to, but I can forge one better than anyone alive."',options:[{text:'"I\'ll remember that."',next:null}]}}},
rook:{name:'Rook',title:'The Blacksmith',desc:'A burly man with a leather apron tends a roaring forge. Sparks fly as he shapes glowing metal.',
  shop:{stock:[{key:'broadsword',price:32},{key:'war_hammer',price:45},{key:'halberd',price:40},{key:'longbow',price:35},{key:'crossbow',price:45},{key:'throwing_knives',price:30}]},
  dialogue:{
    initial:{text:'"Name\'s Rook. I make things that kill things. Simple as that. Need something?"',options:[{text:'"Show me what you\'ve got."',next:'shop_node'},{text:'"Maybe later."',next:null}]},
    returning:{text:'"You again. Good — means you\'re still alive. My work holds up, eh?"',options:[{text:'"Let me see your stock."',next:'shop_node'},{text:'"Just saying hello."',next:null}]},
    shop_node:{text:'"Every weapon here has drawn blood. They\'re proven."',effect:'shop',options:[{text:'"That\'ll do."',next:null}]}}},
thorne:{name:'Thorne',title:'The Monster Hunter',desc:'A lean man in scarred leather sits sharpening a long knife. His eyes are old beyond his years.',
  dialogue:{
    initial:{text:'"You have the look of someone who fights things that shouldn\'t exist. I\'m Thorne. I\'ve been hunting monsters since before you were born. Want some advice?"',options:[{text:'"Tell me about the enemies here."',next:'tips'},{text:'"What\'s the worst thing you\'ve fought?"',next:'worst'},{text:'"No thanks."',next:null}]},
    returning:{text:'"Still breathing? Good. What do you need?"',options:[{text:'"Combat advice."',next:'tips'},{text:'"Nothing. Just checking in."',next:null}]},
    tips:{text:'"Watch for debuffs — poison, bleed, burn, curse, blind, stun. Carry cures. Block halves damage. And never fight something two tiers above you unless you have to."',options:[{text:'"Noted."',next:null}]},
    worst:{text:'"An Elder Dragon in the Ashen Waste. Took three of us. I\'m the only one who walked out, and I left an arm behind. Don\'t be a hero — be smart."',options:[{text:'"I\'ll be careful."',next:null}]}}},
old_sana:{name:'Old Sana',title:'The Fortune Teller',desc:'A hunched figure in shawls sits behind a table covered in bones and dried flowers. Milky eyes fix on you.',
  dialogue:{
    initial:{text:'"Ah, the universe sends me another soul to read. Sit. Let Old Sana see what the bones say about you."',options:[{text:'"Read my fortune."',next:'fortune'},{text:'"I don\'t believe in fortunes."',next:'skeptic'},{text:'"Not today."',next:null}]},
    returning:{text:'"The bones shift. Your fate is not yet written. Shall I read again?"',options:[{text:'"Read them."',next:'fortune'},{text:'"Another time."',next:null}]},
    fortune:{text:'"I see fire and stone in your future. A choice between mercy and power. The wasteland calls, but not all who answer return. Carry cures — you will need them."',options:[{text:'"...Thank you."',next:null}]},
    skeptic:{text:'"Belief is irrelevant, dear. The bones speak whether you listen or not. But I see stubbornness in you — that will serve you well where you\'re going."',options:[{text:'"Fair enough."',next:null}]}}},
captain_vane:{name:'Captain Vane',title:'Guard Captain',desc:'A stern woman in battered plate armor stands at the guard post, a map of the region pinned to the wall behind her.',
  dialogue:{
    initial:{text:'"You look capable. I\'m Captain Vane, head of the garrison. We\'re spread thin. If you\'re looking for work, the bounty board at the tavern has postings. But if you want the truly dangerous marks, come see me."',options:[{text:'"What dangerous marks?"',next:'marks'},{text:'"Tell me about the garrison."',next:'garrison'},{text:'"I\'ll keep that in mind."',next:null}]},
    returning:{text:'"Back for more? The board\'s always got something."',options:[{text:'"What\'s the situation?"',next:'marks'},{text:'"Just passing through."',next:null}]},
    marks:{text:'"Tier 4 and 5 creatures — Death Knights, Void Stalkers, worse. They come from beyond the mountains. The Ashen Waste breeds horrors. Only the strong survive out there."',options:[{text:'"I\'ll handle it."',next:null}]},
    garrison:{text:'"Twenty soldiers and this stone wall. That\'s all that stands between the settlements and what lurks in the dark. We do our best."',options:[{text:'"You do good work."',next:null}]}}},
whisper:{name:'Whisper',title:'The Informant',desc:'A hooded figure leans against the wall in the shadows. You almost didn\'t see them.',
  shop:{stock:[{key:'shadow_cloak',price:40},{key:'throwing_knives',price:32},{key:'antidote',price:8},{key:'smelling_salts',price:8},{key:'eye_drops',price:8}]},
  dialogue:{
    initial:{text:'"...You found me. That\'s already more than most can say. I\'m Whisper. I deal in things people don\'t want seen. Rare goods, useful information. Interested?"',options:[{text:'"Show me what you have."',next:'shop_node'},{text:'"What information?"',next:'info'},{text:'"I\'ll pass."',next:null}]},
    returning:{text:'"You know where to find me. What do you need?"',options:[{text:'"Your wares."',next:'shop_node'},{text:'"Any news?"',next:'info'},{text:'"Nothing."',next:null}]},
    shop_node:{text:'"Discreet purchases. No questions asked."',effect:'shop',options:[{text:'"Done."',next:null}]},
    info:{text:'"The Ashen Waste — there\'s a witch out there, Grizelda. She sells things you can\'t find anywhere else. And deeper in, a hermit who knows the old history. Both worth finding, if you survive the trip."',options:[{text:'"Good to know."',next:null}]}}},
brother_cedric:{name:'Brother Cedric',title:'Traveling Cleric',desc:'A man in simple brown robes sits by the road, a worn holy symbol around his neck. His pack is full of scrolls and vials.',
  shop:{stock:[{key:'purification_scroll',price:12},{key:'antidote',price:8},{key:'bandage',price:8},{key:'burn_salve',price:8},{key:'ghpot',price:20},{key:'elixir',price:25}]},
  dialogue:{
    initial:{text:'"Blessings, traveler. I am Brother Cedric, a wandering cleric of the old faith. I carry healing supplies and cures for those the road has wounded. May I be of service?"',options:[{text:'"Heal me, please."',next:'heal_node'},{text:'"Show me your supplies."',next:'shop_node'},{text:'"Tell me of your faith."',next:'faith'},{text:'"Not now, thank you."',next:null}]},
    returning:{text:'"The road brings you back. How may I serve?"',options:[{text:'"Heal me."',next:'heal_node'},{text:'"Your supplies."',next:'shop_node'},{text:'"Just resting."',next:null}]},
    heal_node:{text:'"By the light that endures, be made whole."',effect:'heal',options:[{text:'"Thank you, Brother."',next:null}]},
    shop_node:{text:'"Take what you need. I ask only fair coin to continue my work."',effect:'shop',options:[{text:'"That\'s all."',next:null}]},
    faith:{text:'"The old gods are quiet, but their light remains in the world — in healing, in mercy, in the courage to face darkness. I carry that light where I can."',options:[{text:'"A noble calling."',next:null}]}}},
grizelda:{name:'Grizelda',title:'The Swamp Witch',desc:'A hunched woman stirs a bubbling cauldron over a sickly green fire. The air smells of sulfur and strange herbs.',
  shop:{stock:[{key:'mushroom_brew',price:8},{key:'antidote',price:6},{key:'burn_salve',price:8},{key:'strength_tonic',price:10},{key:'focus_draught',price:10},{key:'elixir',price:22}]},
  dialogue:{
    initial:{text:'"Heh heh... a visitor. Don\'t get many out here. I\'m Grizelda. The locals call me witch — I prefer \'herbalist with unconventional methods.\' Want to buy something useful?"',options:[{text:'"What do you sell?"',next:'shop_node'},{text:'"Why do you live out here?"',next:'why'},{text:'"I\'ll be going."',next:null}]},
    returning:{text:'"Back for more of my brews? Smart. The waste eats the unprepared."',options:[{text:'"Show me your potions."',next:'shop_node'},{text:'"Any wisdom?"',next:'wisdom'},{text:'"Just visiting."',next:null}]},
    shop_node:{text:'"Everything here is hand-brewed. Side effects are... minimal."',effect:'shop',options:[{text:'"Done."',next:null}]},
    why:{text:'"The swamp provides. Rare fungi, toxic herbs, things that grow nowhere else. Besides, the monsters leave me alone — professional courtesy between things that scare people."',options:[{text:'"...Fair enough."',next:null}]},
    wisdom:{text:'"Burns are the worst out here. Carry salves. And if you meet the Elder Dragon... run. Or don\'t. I\'ll brew something nice for your memorial."',options:[{text:'"Encouraging."',next:null}]}}},
durak:{name:'Durak',title:'The Orc Veteran',desc:'A massive orc with grey-streaked tusks sits on a bench, sharpening a notched greataxe.',
  shop:{stock:[{key:'bone_cleaver',price:55},{key:'war_hammer',price:45},{key:'halberd',price:40},{key:'padded_armor',price:18},{key:'strength_tonic',price:10}]},
  dialogue:{
    initial:{text:'"You look at Durak like he is monster. Durak is veteran. Fought in three wars. Won two. The third... we don\'t talk about the third. You want weapons? Durak has weapons."',options:[{text:'"Show me your weapons."',next:'shop_node'},{text:'"Tell me about the wars."',next:'wars'},{text:'"I\'ll pass."',next:null}]},
    returning:{text:'"Durak remembers you. Still alive. Good. Need steel?"',options:[{text:'"Your weapons."',next:'shop_node'},{text:'"Any stories?"',next:'wars'},{text:'"Not today."',next:null}]},
    shop_node:{text:'"Durak\'s weapons are heavy. Heavy is good. Heavy means dead enemy."',effect:'shop',options:[{text:'"Thanks, Durak."',next:null}]},
    wars:{text:'"First war was against the undead. Second was trolls. Both we won with axe and fury. The third... against the dragons. Nobody wins against dragons. You just survive."',options:[{text:'"I\'ll remember that."',next:null}]}}},
finn:{name:'Finn',title:'Tavern Boy',desc:'A scrawny boy of perhaps twelve sweeps the tavern floor. He looks up with wide, curious eyes.',
  dialogue:{
    initial:{text:'"Are you an adventurer? A real one? I\'ve never met a real adventurer before! Miss Brynn says they come through sometimes but most of them don\'t come back. Are you going to come back?"',options:[{text:'"I plan to."',next:'plan'},{text:'"What can you tell me about this place?"',next:'about'},{text:'"Shouldn\'t you be sweeping?"',next:'sweep'}]},
    returning:{text:'"You came back! I knew it! Do you have any stories?"',options:[{text:'"Maybe later, Finn."',next:null},{text:'"What\'s new around here?"',next:'news'}]},
    plan:{text:'"That\'s what they all say. But you look tougher than the last one. He was a wizard — sneezed every time he cast a spell. Not very intimidating."',options:[{text:'"I\'ll do better than that."',next:null}]},
    about:{text:'"The tavern\'s been here forever. Miss Brynn runs it. Elara makes weapons in the market. Captain Vane keeps us safe. And there\'s a creepy person in the cellar — Whisper. Don\'t tell anyone I told you."',options:[{text:'"Your secret\'s safe."',next:null}]},
    sweep:{text:'"Oh! Right! Sorry!"',options:[{text:'"No worries."',next:null}]},
    news:{text:'"I heard Captain Vane talking about something big beyond the mountains. An \'Elder Dragon.\' She looked scared, and Captain Vane is NEVER scared."',options:[{text:'"Interesting."',next:null}]}}},
hermit:{name:'The Hermit',title:'Keeper of Old Lore',desc:'An ancient figure in tattered robes sits cross-legged in a cave, surrounded by crumbling books and carved stones.',
  dialogue:{
    initial:{text:'"A living soul, here in the waste. How unexpected. I am called the Hermit, though I had a name once. I keep the old stories. Would you hear them?"',options:[{text:'"Tell me the history."',next:'history'},{text:'"What happened to this land?"',next:'land'},{text:'"I should go."',next:null}]},
    returning:{text:'"You return. The stories are always here. What would you know?"',options:[{text:'"Tell me more."',next:'history'},{text:'"About the dragons."',next:'dragons'},{text:'"Nothing. Just visiting."',next:null}]},
    history:{text:'"This was green once, before the dragon wars. The Elder Dragon burned it to ash in a single night. The kingdoms fought back — they built the Constructs, the golems of iron and stone. But even those couldn\'t stop the fire. Now only ash remains."',options:[{text:'"Is the dragon still here?"',next:'dragons'}]},
    dragons:{text:'"The Elder Dragon sleeps in the Throne of Ashes, at the heart of the waste. It wakes when it hungers. And it always hungers. If you go there... bring fire resistance. And say your prayers."',options:[{text:'"Thank you, Hermit."',next:null}]},
    land:{text:'"Volcanic eruptions, dragon fire, and centuries of neglect. The Ashen Waste is what remains when civilization burns. But life persists — the witch, the creatures, even me. Stubborn things, we living."',options:[{text:'"There\'s hope, then."',next:null}]}}},
commander_ashveil:{name:'Commander Ashveil',title:'Garrison Commander',desc:'A grizzled soldier with a burn-scarred face stands at the gate, surveying the scorched landscape beyond.',
  dialogue:{
    initial:{text:'"You made it through the mountains. That alone earns my respect. I\'m Commander Ashveil, last commander of the Ashen Gate garrison. Beyond here lies the waste — volcanic, hostile, and crawling with things that burn."',options:[{text:'"What lies ahead?"',next:'ahead'},{text:'"Any supplies?"',next:'supplies'},{text:'"I\'m ready."',next:null}]},
    returning:{text:'"Still alive? Good. The waste hasn\'t claimed you yet."',options:[{text:'"What\'s the situation?"',next:'ahead'},{text:'"I need healing."',next:'heal_node'},{text:'"I\'m heading back out."',next:null}]},
    ahead:{text:'"The Scorched Road leads to Cinderhaven — what\'s left of it. Beyond that, the Blighted Marsh, the Old Keep, and deeper still, the Ashen Spire. At the end... the Throne of Ashes. The Elder Dragon. Don\'t go there unless you\'re prepared to die."',options:[{text:'"I\'ll be careful."',next:null}]},
    supplies:{text:'"I can offer rest and healing. Beyond that, you\'re on your own. The witch in the swamp — Grizelda — she might have what you need."',options:[{text:'"Thank you."',next:null}]},
    heal_node:{text:'"Rest here. You\'ll need your strength."',effect:'heal',options:[{text:'"Thank you, Commander."',next:null}]}}}
};

const SCENE_DATA={
// === THE MUDDY TRAIL (11 scenes) ===
trailhead:{name:'The Trailhead',subtitle:'Where the road ends and the wild begins',
  description:'The muddy trail stretches northward into a dense, fog-choked forest. The air is thick with wet earth and decay. A half-rotted sign reads: \u201cBeware \u2014 creatures ahead.\u201d',
  npcs:['aldric'],
  exits:{forward:{scene:'midway',label:'Midway on the Trail',discovered:true},tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
midway:{name:'Midway on the Trail',subtitle:'Where the trees close in',
  description:'The trail narrows between gnarled trees whose branches interlock overhead. Mud sucks at your boots with every step. To the east, murky water glints through the undergrowth.',
  npcs:[],
  exits:{forward:{scene:'ooze',label:'Stay on Trail',discovered:true},bog:{scene:'whispering_bog',label:'Search the Bog',discovered:true},back:{scene:'trailhead',label:'The Trailhead',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){if(!r.ss.pouch)UI.addN('Something glints in the mud \u2014 a leather pouch, half-buried and forgotten.','f')},combat:null},
  actions:[{id:'search',label:'Search Pouch',desc:'The leather pouch in the mud',condition(r){return!r.ss.pouch}}]},
ooze:{name:'Ambush!',subtitle:null,
  description:'The trail opens into a clearing. The mud bubbles unnaturally.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'gray_ooze'}},
post_ooze:{name:'After the Battle',subtitle:'The silence of victory',
  description:'The remains of the Gray Ooze spread across the trail in a steaming, acrid puddle. The forest is quiet.',
  npcs:[],
  exits:{forward:{scene:'spider_ambush',label:'Deeper Into the Woods',discovered:true},back:{scene:'midway',label:'Midway on the Trail',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){
    if(!r.ss.oozeSearch1)UI.addN('Something solid rests within the dissolving remains.','f');
    else if(!r.ss.oozeSearch2)UI.addN('The remains still glisten. Perhaps there is more to find.','f')},combat:null},
  actions:[
    {id:'search',label:'Search Remains',desc:'Something solid in the ooze',condition(r){return!r.ss.oozeSearch1}},
    {id:'search',label:'Search Again',desc:'Look more carefully',condition(r){return r.ss.oozeSearch1&&!r.ss.oozeSearch2}}]},
spider_ambush:{name:'Webbed Clearing',subtitle:null,
  description:'Thick webs drape the trees like funeral shrouds. Something skitters in the canopy above.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'giant_spider'}},
post_spider:{name:'The Silken Graveyard',subtitle:'Where silk becomes shroud',
  description:'The spider\u2019s corpse twitches once, then stills. Shredded webs hang limp from the branches. Old bones, wrapped in silk, litter the clearing floor.',
  npcs:[],
  exits:{forward:{scene:'wolf_den',label:'The Dark Hollow',discovered:true},back:{scene:'post_ooze',label:'After the Battle',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){
    if(!r.ss.spiderSearch1)UI.addN('Something glints within the webbed remains.','f')},combat:null},
  actions:[{id:'search_spider',label:'Search Webs',desc:'Something caught in the silk',condition(r){return!r.ss.spiderSearch1}}]},
wolf_den:{name:'The Dark Hollow',subtitle:null,
  description:'The trail dips into a rocky hollow. Claw marks score the stone. A low growl rumbles from the shadows.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'dire_wolf'}},
whispering_bog:{name:'Whispering Bog',subtitle:null,
  description:'Murky water seeps between twisted roots. Mist hangs low. Something stirs beneath the surface \u2014 a pale shape rises from the depths.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'bog_wraith'}},
post_bog:{name:'The Bog, Calm',subtitle:'Where the mist retreats',
  description:'The wraith dissolves into tendrils of fog. The water stills. The marsh holds its secrets, but for now it is quiet.',
  npcs:[],
  exits:{back:{scene:'midway',label:'Back to the Trail',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){
    if(!r.ss.bogSearch1)UI.addN('Strange herbs float near where the wraith fell. Perhaps usable.', 'f')},combat:null},
  actions:[{id:'search_bog',label:'Gather Herbs',desc:'Floating herbs from the marsh',condition(r){return!r.ss.bogSearch1}}]},
post_wolf:{name:'The Hollow, After',subtitle:'Where silence settles like dust',
  description:'The wolf lies still. Blood darkens the stone. The forest holds its breath, as if acknowledging what you\u2019ve done.',
  npcs:[],
  exits:{forward:{scene:'trail_end',label:"Trail's End",discovered:true},back:{scene:'post_spider',label:'The Silken Graveyard',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){
    if(!r.ss.wolfSearch1)UI.addN('The wolf\u2019s den is littered with old supplies from less fortunate travelers.','f')},combat:null},
  actions:[{id:'search_wolf',label:'Search Den',desc:'Scattered supplies among the bones',condition(r){return!r.ss.wolfSearch1}}]},
trail_end:{name:"Trail's End",subtitle:'Where the forest breathes again',
  description:'The forest thins and the trail widens to a mossy clearing lit by dappled sunlight. A small stone shrine stands at the center, covered in climbing ivy.',
  npcs:['mira','garrett'],exits:{tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null},
  actions:[{id:'rest',label:'Rest Here',desc:'Your journey is complete',condition(r){return!!r.ss.mira}}]},

// === THE IRON HOLLOWS (9 scenes) ===
ih_entrance:{name:'The Iron Hollows',subtitle:'Where the mountain swallows the light',
  description:'A jagged rift opens in the mountainside. The air is cold and smells of rust and old stone. Torchlight flickers from somewhere deep within.',
  npcs:['torgun'],
  exits:{forward:{scene:'ih_tunnels',label:'The Winding Tunnels',discovered:true},tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
ih_tunnels:{name:'The Winding Tunnels',subtitle:'Where echoes replace shadows',
  description:'Narrow passages twist between pillars of raw iron ore. Pick marks scar every surface. The ceiling drips rust-colored water.',
  npcs:[],
  exits:{forward:{scene:'ih_crawler_lair',label:'Deeper In',discovered:true},back:{scene:'ih_entrance',label:'The Iron Hollows',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){if(!r.ss.ihTunnelSearch)UI.addN('A broken crate lies wedged between the rocks. Something clinks inside.','f')},combat:null},
  actions:[{id:'search_ih_tunnels',label:'Search Crate',desc:'A broken crate between the rocks',condition(r){return!r.ss.ihTunnelSearch}}]},
ih_crawler_lair:{name:'The Nest',subtitle:null,
  description:'The tunnel opens into a cavern thick with a sour, organic stench. Pale shapes shift in the darkness.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'cave_crawler'}},
ih_post_crawler:{name:'The Shattered Nest',subtitle:'Where chitin crunches underfoot',
  description:'The crawler lies still, its many legs curled inward. Broken eggs and dried slime coat the walls.',
  npcs:[],
  exits:{forward:{scene:'ih_shade_hall',label:'The Shade Hall',discovered:true},back:{scene:'ih_tunnels',label:'The Winding Tunnels',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){if(!r.ss.ihCrawlerSearch)UI.addN('Something metallic gleams in the creature\u2019s nest.','f')},combat:null},
  actions:[{id:'search_ih_crawler',label:'Search Nest',desc:'Something metallic in the debris',condition(r){return!r.ss.ihCrawlerSearch}}]},
ih_shade_hall:{name:'The Shade Hall',subtitle:null,
  description:'A vast hall of carved stone pillars. The torchlight dims. Shadows move where no one stands.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'mine_shade'}},
ih_post_shade:{name:'The Hall, Emptied',subtitle:'Where silence returns to stone',
  description:'The shade dissolves into motes of dark light. The hall is vast and cold and terribly still.',
  npcs:[],
  exits:{forward:{scene:'ih_forge',label:'The Deep Forge',discovered:true},back:{scene:'ih_post_crawler',label:'The Shattered Nest',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){UI.addN('The air grows warmer as you approach the forge. A faint orange glow pulses ahead.','f')},combat:null}},
ih_forge:{name:'The Deep Forge',subtitle:null,
  description:'A colossal forge fills the cavern, its fires still burning after centuries. Standing before the anvil is a hulking figure of living iron.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'iron_golem'}},
ih_post_golem:{name:'The Forge Falls Silent',subtitle:'Where iron rests at last',
  description:'The golem crumbles into a heap of cooling iron. The forge\u2019s flames gutter and dim. For the first time in ages, the mountain is quiet.',
  npcs:[],
  exits:{forward:{scene:'ih_exit',label:'Toward Daylight',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){if(!r.ss.ihGolemSearch)UI.addN('Among the golem\u2019s remains, a battered flask rolls free.','f')},combat:null},
  actions:[{id:'search_ih_golem',label:'Search Remains',desc:'A flask among the rubble',condition(r){return!r.ss.ihGolemSearch}}]},
ih_exit:{name:'Daylight',subtitle:'Where the mountain lets you go',
  description:'A crack of light widens into a blinding exit. Wind rushes in, carrying the scent of pine and open sky. You made it through the Iron Hollows.',
  npcs:[],exits:{tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null},
  actions:[{id:'leave_hollows',label:'Leave the Hollows',desc:'Your journey is complete',condition(){return true}}]},

// === TAVERN SETTLEMENT (4 scenes) ===
tavern_hub:{name:'The Hearthstone Tavern',subtitle:'Where the weary find warmth',
  description:'A sturdy stone building stands at the crossroads, its chimney trailing woodsmoke into the grey sky. Inside, a fire crackles in a massive hearth. A weathered board near the door is pinned with notices and bounties.',
  npcs:['brynn','finn'],
  exits:{trail:{scene:'trailhead',label:'The Muddy Trail',discovered:true},hollows:{scene:'ih_entrance',label:'The Iron Hollows',discovered:true},market:{scene:'market_square',label:'The Market Square',discovered:true},guard:{scene:'guard_post',label:'The Guard Post',discovered:true},cellar:{scene:'tavern_cellar',label:'The Cellar',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null},
  actions:[{id:'bounty_board',label:'Check the Bounty Board',desc:'See available bounties and quests',condition(){return true}}]},
market_square:{name:'The Market Square',subtitle:'Where steel and coin change hands',
  description:'An open area between stone buildings, bustling with the clangor of the forge and the murmur of trade. Weapon racks and armor stands fill every available space.',
  npcs:['elara','rook','durak','brother_cedric'],
  exits:{tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
guard_post:{name:'The Guard Post',subtitle:'Where vigilance never sleeps',
  description:'A fortified stone building overlooking the road. Maps and bounty notices cover the walls. Soldiers patrol the perimeter in shifts.',
  npcs:['captain_vane','thorne'],
  exits:{tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
tavern_cellar:{name:'The Cellar',subtitle:'Where shadows have ears',
  description:'A damp, dimly-lit space beneath the tavern. Barrels of ale line the walls, but the far corner holds something else \u2014 a hooded figure, barely visible in the gloom.',
  npcs:['whisper','old_sana'],
  exits:{tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},

// === THE ASHEN WASTE (10 scenes) ===
ash_gate:{name:'The Ashen Gate',subtitle:'Where the mountains end and fire begins',
  description:'A stone fortress marks the edge of the known world. Beyond its gates, the sky turns orange and the ground is cracked black glass. The air smells of sulfur.',
  npcs:['commander_ashveil'],
  exits:{forward:{scene:'ash_road',label:'The Scorched Road',discovered:true},tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
ash_road:{name:'The Scorched Road',subtitle:'Where nothing grows',
  description:'A road of fused glass and volcanic rock stretches through a barren landscape. Heat shimmers distort the horizon. Something skitters between the rocks.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'ember_beetle'}},
ash_post_road:{name:'The Road Continues',subtitle:'Where ash drifts like snow',
  description:'The beetle\'s carapace cools on the glass road. Ahead, the ruins of a village emerge from the haze.',
  npcs:[],
  exits:{forward:{scene:'ash_village',label:'Cinderhaven Ruins',discovered:true},side:{scene:'witch_hut',label:'A Path to the Swamp',discovered:true},back:{scene:'ash_gate',label:'The Ashen Gate',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
ash_village:{name:'Cinderhaven Ruins',subtitle:'Where a town once stood',
  description:'Blackened walls and collapsed roofs mark what was once a thriving village. A few hardy souls cling to existence among the ruins. A cauldron bubbles in a makeshift shelter.',
  npcs:['grizelda'],
  exits:{forward:{scene:'ash_swamp',label:'The Blighted Marsh',discovered:true},side:{scene:'hermit_cave',label:'A Cave in the Cliffs',discovered:true},back:{scene:'ash_post_road',label:'The Scorched Road',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
ash_swamp:{name:'The Blighted Marsh',subtitle:null,
  description:'Thick, foul-smelling mud churns with bubbles of volcanic gas. Twisted fungi tower overhead, releasing clouds of choking spores. Something massive moves beneath the surface.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'fungal_horror'}},
ash_post_swamp:{name:'Beyond the Marsh',subtitle:'Where the air clears',
  description:'The swamp thins into cracked, dry earth. The Old Keep\'s silhouette rises against the orange sky like a jagged tooth.',
  npcs:[],
  exits:{forward:{scene:'ash_ruins',label:'The Old Keep',discovered:true},back:{scene:'ash_village',label:'Cinderhaven Ruins',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
ash_ruins:{name:'The Old Keep',subtitle:null,
  description:'Crumbling stone walls surround a courtyard choked with ash. A suit of armor stands in the center, impossibly still. Then it turns its head.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'corrupted_knight'}},
ash_post_ruins:{name:'The Keep, Fallen',subtitle:'Where duty ends',
  description:'The corrupted knight crumbles into rust and spite. Beyond the keep, a spiral of dark stone rises into the orange sky \u2014 the Ashen Spire.',
  npcs:[],
  exits:{forward:{scene:'ash_tower',label:'The Ashen Spire',discovered:true},back:{scene:'ash_post_swamp',label:'Beyond the Marsh',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){if(!r.ss.ashRuinsSearch)UI.addN('The knight\'s armor holds something \u2014 a flask, still intact.','f')},combat:null},
  actions:[{id:'search_ash_ruins',label:'Search Remains',desc:'Something in the armor',condition(r){return!r.ss.ashRuinsSearch}}]},
ash_tower:{name:'The Ashen Spire',subtitle:null,
  description:'A tower of black obsidian spirals upward. Inside, the heat is unbearable. Something massive breathes in the chamber above \u2014 a rhythmic, furnace-like pulse.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'ash_wyrm'}},
ash_post_tower:{name:'The Spire, Silenced',subtitle:'Where fire dies',
  description:'The wyrm falls from the spire in a cascade of sparks and ash. Through the smoke, a doorway leads to a vast chamber \u2014 the Throne of Ashes.',
  npcs:[],
  exits:{forward:{scene:'ash_throne',label:'The Throne of Ashes',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
ash_throne:{name:'The Throne of Ashes',subtitle:null,
  description:'A cavern of volcanic glass, lit by rivers of molten rock. At its center, coiled upon a throne of fused bone, lies the Elder Dragon. Its eye opens. It has been waiting.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:'elder_dragon'}},
ash_exit:{name:'Dawn Breaks',subtitle:'Where fire surrenders to light',
  description:'The Elder Dragon falls. The ground shakes. Through the smoke and ash, a crack of light appears \u2014 daylight, real daylight. The Ashen Waste will heal, slowly. You emerge, changed.',
  npcs:[],exits:{tavern:{scene:'tavern_hub',label:'The Hearthstone Tavern',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null},
  actions:[{id:'leave_waste',label:'Leave the Ashen Waste',desc:'Your journey is complete',condition(){return true}}]},

// === SIDE LOCATIONS ===
witch_hut:{name:"Grizelda's Hut",subtitle:'Where the swamp provides',
  description:'A crooked hut on stilts rises from the marsh, festooned with hanging herbs and animal skulls. Smoke curls from a chimney made of stacked skulls.',
  npcs:['grizelda'],
  exits:{back:{scene:'ash_post_road',label:'The Scorched Road',discovered:true}},
  events:{onFirstVisit:null,onEnter:null,combat:null}},
hermit_cave:{name:"The Hermit's Cave",subtitle:'Where memory endures',
  description:'A shallow cave in the volcanic cliffs, its walls covered in ancient writings and carved symbols. The air is cool and still \u2014 a sanctuary from the heat.',
  npcs:['hermit'],
  exits:{back:{scene:'ash_village',label:'Cinderhaven Ruins',discovered:true}},
  events:{onFirstVisit:null,onEnter(r){if(!r.ss.hermitVisit){r.ss.hermitVisit=true;
    if(r.bp.length<6){r.bp.push({...ITEMS.elixir});UI.addN('The Hermit offers you a gift \u2014 an Elixir, old but potent.','s')}
    GS.saveA()}},combat:null}},

// === BOUNTY ARENA ===
bounty_arena:{name:'Bounty Hunt',subtitle:null,
  description:'You set out to fulfill your bounty.',
  npcs:[],exits:{},
  events:{onFirstVisit:null,onEnter:null,combat:null}}
};

const BOUNTIES={
// === ORIGINAL BOUNTIES (7) ===
ooze_hunt:{name:'Ooze Hunt',enemy:'gray_ooze',tier:1,goldReward:10,xpReward:30,desc:'Clear the slimes from the trail.'},
bog_sweep:{name:'Bog Sweep',enemy:'bog_wraith',tier:1,goldReward:12,xpReward:35,desc:'Lay a restless spirit to rest.'},
spider_silk:{name:'Spider Silk',enemy:'giant_spider',tier:2,goldReward:18,xpReward:50,desc:'Harvest silk from the forest spiders.'},
wolf_cull:{name:'Wolf Cull',enemy:'dire_wolf',tier:2,goldReward:22,xpReward:60,desc:'The wolves grow bold. Thin the pack.'},
crawler_purge:{name:'Crawler Purge',enemy:'cave_crawler',tier:3,goldReward:28,xpReward:70,desc:'Clear the tunnels of crawling horrors.'},
shade_hunt:{name:'Shade Hunt',enemy:'mine_shade',tier:4,goldReward:35,xpReward:90,desc:'Banish the flickering shadow from the deep halls.'},
iron_challenge:{name:'Iron Challenge',enemy:'iron_golem',tier:5,goldReward:50,xpReward:120,desc:'Test your mettle against a construct of living iron.'},

// === NEW BOUNTIES (18) ===
rat_extermination:{name:'Rat Extermination',enemy:'moss_rat',tier:1,goldReward:8,xpReward:20,desc:'The moss rats are overrunning the trail. Thin them out.'},
toad_hunt:{name:'Toad Hunt',enemy:'marsh_toad',tier:1,goldReward:9,xpReward:22,desc:'The marsh toads are blocking the bog path.'},
beetle_crush:{name:'Beetle Crush',enemy:'ember_beetle',tier:1,goldReward:9,xpReward:25,desc:'Ember beetles are burning the trailside brush.'},
bat_clearance:{name:'Bat Clearance',enemy:'tunnel_bat',tier:1,goldReward:8,xpReward:20,desc:'Clear the bats from the upper tunnels.'},
snake_hunt:{name:'Snake Hunt',enemy:'venomfang_snake',tier:2,goldReward:18,xpReward:50,desc:'A venomfang has been spotted near the trail.'},
hound_hunt:{name:'Hound Hunt',enemy:'shadow_hound',tier:2,goldReward:20,xpReward:55,desc:'Shadow hounds prowl the forest at night.'},
fungal_purge:{name:'Fungal Purge',enemy:'fungal_horror',tier:2,goldReward:18,xpReward:50,desc:'Fungal horrors spread sickness. Destroy them.'},
lizard_hunt:{name:'Lizard Hunt',enemy:'ironscale_lizard',tier:2,goldReward:20,xpReward:55,desc:'An ironscale lizard guards the lower caves.'},
ghoul_hunt:{name:'Ghoul Hunt',enemy:'ghoul',tier:2,goldReward:20,xpReward:55,desc:'Ghouls have risen in the old cemetery.'},
troll_bounty:{name:'Troll Bounty',enemy:'rock_troll',tier:2,goldReward:24,xpReward:60,desc:'A rock troll has claimed the bridge.'},
flame_hunt:{name:'Flame Hunt',enemy:'flame_elemental',tier:3,goldReward:30,xpReward:75,desc:'A flame elemental roams the volcanic vents.'},
banshee_hunt:{name:'Banshee Hunt',enemy:'banshee',tier:3,goldReward:30,xpReward:75,desc:'A banshee wails in the ruins. Silence her.'},
knight_hunt:{name:'Fallen Knight',enemy:'corrupted_knight',tier:3,goldReward:32,xpReward:80,desc:'A corrupted knight haunts the old keep.'},
wyvern_hunt:{name:'Wyvern Hunt',enemy:'wyvern',tier:3,goldReward:35,xpReward:85,desc:'A wyvern nests in the upper cliffs.'},
death_knight_bounty:{name:'Death Knight Bounty',enemy:'death_knight',tier:4,goldReward:42,xpReward:100,desc:'A death knight has been sighted. Destroy it.'},
void_hunt:{name:'Void Hunt',enemy:'void_stalker',tier:4,goldReward:40,xpReward:95,desc:'A void stalker flickers between realities.'},
wyrm_hunt:{name:'Wyrm Hunt',enemy:'ash_wyrm',tier:4,goldReward:42,xpReward:100,desc:'An ash wyrm terrorizes the scorched road.'},
dragon_hunt:{name:'Dragon Hunt',enemy:'elder_dragon',tier:5,goldReward:80,xpReward:200,desc:'The Elder Dragon itself. Are you ready?'}
};

const QUESTS={
// === ORIGINAL QUESTS (7) ===
first_blood:{name:'First Blood',desc:'Complete any bounty.',trigger:'bounty_complete',count:1,reward:{gold:20,xp:50},oneTime:true},
wolf_slayer:{name:'Wolf Slayer',desc:'Defeat 3 Dire Wolves via bounties.',trigger:'defeat_dire_wolf',count:3,reward:{gold:50,xp:100},oneTime:true},
exterminator:{name:'Exterminator',desc:'Complete 5 bounties of any kind.',trigger:'bounty_complete',count:5,reward:{gold:40,xp:80},oneTime:true},
veteran_hunter:{name:'Veteran Hunter',desc:'Complete 10 bounties total.',trigger:'bounty_complete',count:10,reward:{gold:80,xp:150},oneTime:true},
spider_bane:{name:'Spider Bane',desc:'Defeat 3 Giant Spiders via bounties.',trigger:'defeat_giant_spider',count:3,reward:{gold:45,xp:90},oneTime:true},
shade_walker:{name:'Shade Walker',desc:'Defeat 2 Mine Shades via bounties.',trigger:'defeat_mine_shade',count:2,reward:{gold:60,xp:120},oneTime:true},
ironbreaker:{name:'Ironbreaker',desc:'Defeat the Iron Golem in a bounty.',trigger:'defeat_iron_golem',count:1,reward:{gold:100,xp:200},oneTime:true},

// === NEW QUESTS (10) ===
pest_control:{name:'Pest Control',desc:'Complete 3 tier-1 bounties.',trigger:'bounty_complete',count:3,reward:{gold:30,xp:60},oneTime:true},
monster_slayer:{name:'Monster Slayer',desc:'Complete 15 bounties total.',trigger:'bounty_complete',count:15,reward:{gold:120,xp:250},oneTime:true},
elite_hunter:{name:'Elite Hunter',desc:'Complete 3 tier-4+ bounties.',trigger:'bounty_complete',count:20,reward:{gold:150,xp:300},oneTime:true},
troll_slayer:{name:'Troll Slayer',desc:'Defeat 2 Rock Trolls via bounties.',trigger:'defeat_rock_troll',count:2,reward:{gold:50,xp:100},oneTime:true},
banshee_silencer:{name:'Banshee Silencer',desc:'Defeat 2 Banshees via bounties.',trigger:'defeat_banshee',count:2,reward:{gold:60,xp:120},oneTime:true},
knight_slayer:{name:'Knight Slayer',desc:'Defeat 2 Corrupted Knights via bounties.',trigger:'defeat_corrupted_knight',count:2,reward:{gold:65,xp:130},oneTime:true},
wyrm_slayer:{name:'Wyrm Slayer',desc:'Defeat 2 Ash Wyrms via bounties.',trigger:'defeat_ash_wyrm',count:2,reward:{gold:80,xp:160},oneTime:true},
dragon_slayer:{name:'Dragon Slayer',desc:'Defeat the Elder Dragon in a bounty.',trigger:'defeat_elder_dragon',count:1,reward:{gold:200,xp:400},oneTime:true},
wasteland_explorer:{name:'Wasteland Explorer',desc:'Complete 25 bounties total.',trigger:'bounty_complete',count:25,reward:{gold:200,xp:500},oneTime:true},
legend:{name:'Legend',desc:'Complete 50 bounties total.',trigger:'bounty_complete',count:50,reward:{gold:500,xp:1000},oneTime:true}
};

const DEATH_QUOTES=[
// === ORIGINAL (12) ===
'"Not every path leads home."',
'"The trail remembers those who fall."',
'"Even the bravest meet their end in the mud."',
'"The forest takes what it is owed."',
'"Rest now. The trail goes on without you."',
'"The spider wraps another meal in silk."',
'"The wolves will feast tonight."',
'"Venom and fangs \u2014 the forest\u2019s welcome."',
'"The bog takes back what it gave."',
'"The mountain claims another."',
'"Darkness is patient. You were not."',
'"Iron endures. You did not."',
// === NEW (12) ===
'"The ash remembers no names."',
'"Fire consumes all things, given time."',
'"Even dragons were mortal once. You never stopped being one."',
'"The wasteland takes its toll in flesh and bone."',
'"Curse and flame \u2014 the Ashen Waste\u2019s welcome."',
'"The dead do not rest here. Neither will you."',
'"The Hermit will add your story to the walls."',
'"Grizelda warned you. You didn\u2019t listen."',
'"Commander Ashveil will light a candle. It won\u2019t last."',
'"The Elder Dragon sleeps again. Fed."',
'"You fought well. It wasn\u2019t enough."',
'"The darkness between worlds swallowed you whole."'
];
